# Project: Nave
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o miniwin.o $(RES)
LINKOBJ  = main.o miniwin.o $(RES)
LIBS =  -L"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/lib" -mwindows -lwinmm  
INCS =  -I"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/Wiwiwi/Documents/Dev-CppPortable/App/devcpp/include" 
BIN  = Nave.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Nave.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Nave.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

miniwin.o: miniwin.cpp
	$(CPP) -c miniwin.cpp -o miniwin.o $(CXXFLAGS)
